# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/waLidMigrationSyncPayload/WAWebProtobufLidMigrationSyncPayload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJproto/waLidMigrationSyncPayload/WAWebProtobufLidMigrationSyncPayload.proto\x12$WAWebProtobufLidMigrationSyncPayload\"I\n\x13LIDMigrationMapping\x12\n\n\x02pn\x18\x01 \x02(\x04\x12\x13\n\x0b\x61ssignedLid\x18\x02 \x02(\x04\x12\x11\n\tlatestLid\x18\x03 \x01(\x04\"\x96\x01\n\x1eLIDMigrationMappingSyncPayload\x12R\n\x0fpnToLidMappings\x18\x01 \x03(\x0b\x32\x39.WAWebProtobufLidMigrationSyncPayload.LIDMigrationMapping\x12 \n\x18\x63hatDbMigrationTimestamp\x18\x02 \x01(\x04\x42\x35Z3go.mau.fi/whatsmeow/proto/waLidMigrationSyncPayload')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.waLidMigrationSyncPayload.WAWebProtobufLidMigrationSyncPayload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3go.mau.fi/whatsmeow/proto/waLidMigrationSyncPayload'
  _LIDMIGRATIONMAPPING._serialized_start=116
  _LIDMIGRATIONMAPPING._serialized_end=189
  _LIDMIGRATIONMAPPINGSYNCPAYLOAD._serialized_start=192
  _LIDMIGRATIONMAPPINGSYNCPAYLOAD._serialized_end=342
# @@protoc_insertion_point(module_scope)
