class ProtocolAddress:
    def __init__(self, name: str, device_id: int) -> None: ...
    def name(self) -> str: ...
    def device_id(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
