from typing import Any

class SignalProtocolException(Exception):
    def __init__(self, message: str = "") -> None: ...
    def add_note(self, note: str) -> None: ...
    def with_traceback(self, tb: Any) -> "SignalProtocolException": ...
