name: Go

on: [push, pull_request]

env:
  GOTOOLCHAIN: local

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.23", "1.24"]
    name: Build ${{ matrix.go-version == '1.24' && '(latest)' || '(old)' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Install goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        export PATH="$HOME/go/bin:$PATH"

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

  python-checks:
    name: Python Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # As derived from .python-version in problem description

      - name: Install Python QA Tools
        run: |
          pip install ruff
          pip install mypy
          pip install pytest pytest-cov

      - name: Run Ruff
        run: ruff check pymeow/pymeow

      - name: Run Mypy
        run: mypy pymeow/pymeow --ignore-missing-imports

      - name: Run Pytest with Coverage
        run: pytest pymeow/pymeow/tests --cov=pymeow/pymeow --cov-report=xml --cov-report=term
